server:
  port: 7778
spring:
  cloud:
    stream:
      bindings:
        producer.destination: consumer
        producer.group: consumer-group
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
                virtual-host: /