server:
  port: 7778
spring:
  cloud:
    stream:
      bindings:
        producer.destination: consumer
        producer.group: consumer-group
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                binder:
                  brokers: localhost:9092
                  zk-nodes: localhost:2182
                  auto-add-partitions: true
                  auto-create-topics: true
                  min-partition-count: 1