server:
  port: 7777
spring:
  cloud:
    stream:
      bindings:
        consumer.destination: consumer
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: admin
                virtual-host: /